### ISSUE TITLE
problema a szigetekkel #acidisland-en 

### ISSUE THREAD

**Issue by laci9954** [xtrememiners/BugReport#1]
acidislandon problémák: nem jók a szigetek a playerek a sajt szigetükön nem tudják kinyitni ládájikat, de rombolni építeni tudnak. A szerveren az eső és a víz már nem savas azaz nem sebeznek ami egy acidisland szerveren nem a legjobb. néhány parancs sem müködik pl /ai /ai create nem mindig adja ki a menüt csak 2/3-ik probálkozásra (lehet ez csak nálam van).

**Comment by ressidell** [comment]
Láda nyitható, saját szigeten építeni van jog, eső sebez, víz sebez.
AcidIslanden nincs /ai create mert csak egy fajta template van
/ai szerepe hogy a szigetedre dobjon és elkészítse
